version: '3.7'

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/flask_api
    command: gunicorn -b 0.0.0.0:8000 app
    expose:
      - 8000
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/flask_api/card/static
    ports:
      - 80:80
    links:
      - flask
    depends_on:
      - flask
    dns:
      - 127.0.0.1
    dns_search: localhost

volumes:
  static_volume:
    name: flask_api_static